more script cleanup

diff --git a/bin/dotfiles-backup b/bin/dotfiles-backup
--- a/bin/dotfiles-backup
+++ b/bin/dotfiles-backup
@@ -7,16 +7,20 @@
 
 set -e
 
-TARGET_DIR="${1:-$DOTFILES_BACKUP_DIR}"
+main() {
+  local target_dir="${1:-$DOTFILES_BACKUP_DIR}"
 
-if [ ! -d "${TARGET_DIR}" ]; then
-  echo "Invalid target directory: '${TARGET_DIR}'"
-  exit 1
-fi
+  if [ ! -d "${target_dir}" ]; then
+    echo "Invalid target directory: '${target_dir}'"
+    exit 1
+  fi
 
-rsync \
-  -arv \
-  --delete \
-  --exclude ".git" \
-  "${DOTFILES_DIR}/" \
-  "${TARGET_DIR}"
+  rsync \
+    -arv \
+    --delete \
+    --exclude ".git" \
+    "${DOTFILES_DIR}/" \
+    "${target_dir}"
+}
+
+main "$@"
diff --git a/bin/http-serve b/bin/http-serve
--- a/bin/http-serve
+++ b/bin/http-serve
@@ -5,12 +5,15 @@
 # Usage:
 #  http-serve
 
-http-serve() {
+main() {
   if [ -x "$(command -v python3)" ]; then
     python3 -m http.server
-  else
+  elif [ -x "$(command -v python)" ]; then
     python -m SimpleHTTPServer
+  else
+    echo "Python is required to run this script"
+    exit 1
   fi
 }
 
-http-serve "$@"
+main "$@"
