minor updates
- moving bin specific files
- add back git count alias

diff --git a/modules/dotfiles/libexec/dotfiles-backup b/modules/dotfiles/libexec/dotfiles-backup
--- a/modules/dotfiles/libexec/dotfiles-backup
+++ b/modules/dotfiles/libexec/dotfiles-backup
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/usr/bin/env zsh
 #
 # description:
 #   Backup local machine setups & secrets
@@ -7,4 +7,20 @@
 #   Implement function to backup secrets and local env files
 #
 
-${DOTFILES_DIR}/bin/backup-dotfiles $@
+set -e
+
+TARGET_DIR="${1:-$DOTFILES_BACKUP_DIR}"
+
+if [[ ! -d "${TARGET_DIR}" ]]; then
+  echo "Invalid target directory: '${TARGET_DIR}'"
+  exit 1
+fi
+
+rsync \
+  -arv \
+  --delete \
+  --exclude='.git' \
+  "${DOTFILES_LOCAL_DIR}" \
+  "${TARGET_DIR}"
+
+exit 0
