use main fn

diff --git a/modules/git/.local/bin/git-hooks-restore b/modules/git/.local/bin/git-hooks-restore
--- a/modules/git/.local/bin/git-hooks-restore
+++ b/modules/git/.local/bin/git-hooks-restore
@@ -3,25 +3,30 @@
 #   Restore git hooks from the git-hooks directory
 #
 # Usage:
-#   git-hooks-restore
 #   git hooks-restore
 
-GIT_DIR=$(git rev-parse --show-toplevel 2>/dev/null)
+main() {
+  local git_dir install_path
 
-if [ ! -d "$GIT_DIR" ]; then
-  echo "Error: This is not a git repository"
-  exit 1
-fi
+  git_dir=$(git rev-parse --show-toplevel 2>/dev/null)
 
-GIT_HOOKS_DIR="$GIT_DIR/.git/hooks"
-GIT_INSTALL_PATH="$(realpath "$(which git)" | awk -F'/bin/git' '{print $1}')"
-TEMPLATES_DIR="$GIT_INSTALL_PATH/share/git-core/templates/hooks"
+  if [ ! -d "$git_dir" ]; then
+    echo "Error: This is not a git repository"
+    exit 1
+  fi
 
-if [ ! -d "$TEMPLATES_DIR" ]; then
-  echo "Error: Could not find git templates directory for hooks"
-  exit 1
-fi
+  local hooks_dir="$git_dir/.git/hooks"
+  install_path="$(realpath "$(which git)" | awk -F'/bin/git' '{print $1}')"
+  local templates_dir="$install_path/share/git-core/templates/hooks"
 
-echo "Restoring hooks from $TEMPLATES_DIR to $GIT_HOOKS_DIR"
-mkdir -p "$GIT_HOOKS_DIR"
-cp "$TEMPLATES_DIR"/* "$GIT_HOOKS_DIR"
+  if [ ! -d "$templates_dir" ]; then
+    echo "Error: Could not find git templates directory for hooks"
+    exit 1
+  fi
+
+  echo "Restoring hooks from $templates_dir to $hooks_dir"
+  mkdir -p "$hooks_dir"
+  cp "$templates_dir"/* "$hooks_dir"
+}
+
+main "$@"
